authors:
  Sustainability & AI expert:
    name: Karlo Timmerman RA
    description: CEO & Founder of SKY DUST
    avatar: https://avatars.githubusercontent.com/u/4852235?v=4
    url: https:/linkedin.com/in/karlotimmerman
  Head of Business development:
    name: Nick Nijhuis
    description: Head of Business Development
    avatar: https://i.imgur.com/wO6erNq.jpeg
    url: https://linkedin.com/in/nicknijhuis
